version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: Yarn install, build, and test
          command: |
            yarn install
            yarn build
            yarn test
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}' 
  deploy:
    docker: 
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Build Package 
          command: |
            export BUILD_INFO=build-info.txt
            echo "${CIRCLE_BUILD_NUM}" >> $BUILD_INFO  
            echo "${CIRCLE_SHA1}"      >> $BUILD_INFO 
            echo "$(date -u)"          >> $BUILD_INFO
            export PATTERN="v[0-9]+(\.[0-9]+).*"
            if [[ ${CIRCLE_TAG} =~  ${PATTERN} ]]; then
              export REACT_APP_BASE_URL=${QA_REACT_APP_BASE_URL}
              export REACT_APP_API_URL=${QA_REACT_APP_API_URL}
              export REACT_APP_OKTA_CLIENT_ID=${QA_REACT_APP_OKTA_CLIENT_ID}    
              export REACT_APP_OKTA_ISSUER=${QA_REACT_APP_OKTA_ISSUER}
              export REACT_APP_OKTA_DISABLE_HTTPS_CHECK=${QA_REACT_APP_OKTA_DISABLE_HTTPS_CHECK}
              sed "\
              s|^REACT_APP_BASE_URL=.*$|REACT_APP_BASE_URL=${QA_REACT_APP_BASE_URL}|g;
              s|^REACT_APP_API_URL=.*$|REACT_APP_API_URL=${QA_REACT_APP_API_URL}|g;
              s|^REACT_APP_OKTA_CLIENT_ID=.*$|REACT_APP_OKTA_CLIENT_ID=${QA_REACT_APP_OKTA_CLIENT_ID}|g;
              s|^REACT_APP_OKTA_ISSUER=.*$|REACT_APP_OKTA_ISSUER =${QA_REACT_APP_OKTA_ISSUER}|g;
              s|^REACT_APP_OKTA_DISABLE_HTTPS_CHECK=.*$|REACT_APP_OKTA_DISABLE_HTTPS_CHECK=${QA_REACT_APP_OKTA_DISABLE_HTTPS_CHECK}|g;
              " .env.example > .env
            else
              sed "\
              s|^REACT_APP_BASE_URL=.*$|REACT_APP_BASE_URL=${REACT_APP_BASE_URL}|g;
              s|^REACT_APP_API_URL=.*$|REACT_APP_API_URL=${REACT_APP_API_URL}|g;
              s|^REACT_APP_OKTA_CLIENT_ID=.*$|REACT_APP_OKTA_CLIENT_ID=${REACT_APP_OKTA_CLIENT_ID}|g;
              s|^REACT_APP_OKTA_ISSUER=.*$|REACT_APP_OKTA_ISSUER =${REACT_APP_OKTA_ISSUER}|g;
              s|^REACT_APP_OKTA_DISABLE_HTTPS_CHECK=.*$|REACT_APP_OKTA_DISABLE_HTTPS_CHECK=${REACT_APP_OKTA_DISABLE_HTTPS_CHECK}|g;
              " .env.example > .env
            fi
            cat .env
            yarn install
            yarn build
            cp -f .env build/.env
            cp -f $BUILD_INFO build/$BUILD_INFO
      - run:
          name: Deploy to CloudFront
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            export S3=${DEV_S3}
            export CLOUDFRONT_ID=${DEV_CLOUDFRONT_ID}
            export AWS_REGION=${DEV_AWS_REGION}
            if [[ ${CIRCLE_TAG} =~  ${PATTERN} ]]; then
              echo
              echo "deploy QA build"
              echo
              export S3=${QA_S3}
              export CLOUDFRONT_ID=${QA_CLOUDFRONT_ID}
              export AWS_REGION=${QA_AWS_REGION}
            fi 
            #aws s3 sync --acl bucket-owner-full-control build ${S3} --delete --region ${AWS_REGION} 
            #aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}' 
orbs:
  slack: circleci/slack@3.4.2
workflows:
  ci-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:/v[0-9]+(\.[0-9]+).*/
            branches:
              only: 
                - master
