version: 2.1

commands:
  build_file:
    description: "Build files"
    steps:
      - run: 
          name: Yarn install, build, and test
          command: |
            yarn install
            yarn build
            yarn test
      - run:
          name: "Run  Coverage Reports"
          command: |
            npm test -- --coverage --watchAll=false --collectCoverageFrom=src/**/*js
      - run:
          name: "Run Sonarqube scanner"
          command: |
            export SCAN_VERSION=4.3.0.2102-linux
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SCAN_VERSION}.zip 
            unzip sonar-scanner-cli-${SCAN_VERSION}.zip 
            ./sonar-scanner-${SCAN_VERSION}/bin/sonar-scanner \
             -Dsonar.projectKey=gitwize-fe \
             -Dsonar.sources=. \
             -Dsonar.host.url=https://sunfyre.wizeline.com \
             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
             -Dsonar.login=${SONARQUBE_TOKEN}

  deploy_build:
    steps:
      - run:
          name: Build Package 
          command: |
            export BUILD_INFO=build-info.txt
            echo "${CIRCLE_BUILD_NUM}" >> $BUILD_INFO  
            echo "${CIRCLE_SHA1}"      >> $BUILD_INFO 
            echo "$(date -u)"          >> $BUILD_INFO
            echo ${CIRCLE_TAG}
            export PATTERN="v[0-9]+(\.[0-9]+).*"
            if [[ ${CIRCLE_TAG} =~  ${PATTERN} ]]; then
              export REACT_APP_BASE_URL=${QA_REACT_APP_BASE_URL}
              export REACT_APP_API_URL=${QA_REACT_APP_API_URL}
              export REACT_APP_OKTA_CLIENT_ID=${QA_REACT_APP_OKTA_CLIENT_ID}    
              export REACT_APP_OKTA_ISSUER=${QA_REACT_APP_OKTA_ISSUER}
              export REACT_APP_OKTA_DISABLE_HTTPS_CHECK=${QA_REACT_APP_OKTA_DISABLE_HTTPS_CHECK}
            fi
            yarn install
            yarn build
            cp -f $BUILD_INFO build/$BUILD_INFO
      - run:
          name: Deploy to CloudFront
          command: |
            export S3=${DEV_S3}
            export CLOUDFRONT_ID=${DEV_CLOUDFRONT_ID}
            export AWS_REGION=${DEV_AWS_REGION}
            export PATTERN="v[0-9]+(\.[0-9]+).*"
            echo "${CIRCLE_TAG} ${PATTERN} $REACT_APP_BASE_URL"
            if [[ ${CIRCLE_TAG} =~  ${PATTERN} ]]; then
              echo
              echo "deploy QA build"
              echo
              export S3=${QA_S3}
              export CLOUDFRONT_ID=${QA_CLOUDFRONT_ID}
              export AWS_REGION=${QA_AWS_REGION}
            fi 
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            aws s3 sync --acl bucket-owner-full-control build ${S3} --delete --region ${AWS_REGION} 
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"

jobs:
  build:
    docker: 
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - build_file
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}' 
  deploy:
    docker: 
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - deploy_build
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}' 

  deploy-qa:
    docker:
      - image: circleci/node:lts # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - deploy_build
      - slack/status:
          fail_only: false
          webhook: '${SLACK_WEBHOOK}' 

orbs:
  slack: circleci/slack@3.4.2
workflows:
  ci-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - /deploy-.*/
      - deploy-qa:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+).*/
